osx_image: xcode7.1
sudo: required
language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-ri --no-rdoc
  - gem install xcpretty --no-ri --no-rdoc
script: rake test
